### ISSUE TITLE
[FE] Persist client state

### ISSUE THREAD

**Issue by duongdev** [get6pm/6pm#186]
- [x] Categories
- [x] Wallet accounts
- [x] Budgets
- [x] Transactions
    - [x] Reflect amount by category type (create/update)
- [ ] Auth session
- [x] Clear all cached data when auth user changes

**Comment by bkdev98** [comment]
![fc0c0ef5-a459-4773-993e-e05c7e5763de_text](https://github.com/user-attachments/assets/91869eb8-c2e4-4348-9261-a310a9fad8f0)
